In [2]:
pip install pandas

^C
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting pandas
  Using cached pandas-3.0.6-cp312-cp312-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\users\admin\agentic ai projects\ai\machine learning\venv\lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\agentic ai projects\ai\machine learning\venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.5-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\admin\agentic ai projects\ai\machine learning\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.6-cp312-cp312-win_amd64.whl (9.7 MB)
Using cached tzdata-2026.5-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, pandas
Successfully installed pandas-3.0.6 tzdata-2026.5

In [3]:
import pandas as pd

In [6]:
import numpy as np

In [7]:
labels = ['a', 'b', 'c']
my_list = [10, 20, 30]
#how to create series
arr = np.array([10,20,30])
d = {'a':10, 'b':20, 'c':30}

In [ ]:
ser1 = pd.Series(my_list)
ser1                               #label is index

0    10
1    20
2    30
dtype: int64

In [13]:
ser1 = pd.Series(my_list,index=labels)
ser1

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(arr)      #not 2d as series itself is one D

0    10
1    20
2    30
dtype: int64

In [ ]:
pd.Series(d) #(automatically created index with dictionalry keys)

a    10
b    20
c    30
dtype: int64

In [19]:
s = pd.Series([10, 20, 30, 40, 50])

# Math operations (on all values!)
s * 2       # [20, 40, 60, 80, 100]
s + 5       # [15, 25, 35, 45, 55]
s / 10      # [1, 2, 3, 4, 5]

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
dtype: float64

In [20]:
# Statistics
s.mean()    # 30
s.max()     # 50
s.min()     # 10
s.sum()     # 150
s.std()     # standard deviation

np.float64(15.811388300841896)

In [21]:
# Filter (like list comprehension)
s[s > 25]   # Only values > 25
# Output:
# 2    30
# 3    40
# 4    50

2    30
3    40
4    50
dtype: int64

In [22]:

# Create a Series
prices = pd.Series([100, 200, 150, 250, 300],
                   index=['Apple', 'Banana', 'Orange', 'Mango', 'Grapes'])

# Questions to answer:
# 1. What's the price of Apple?
print(prices['Apple'])

100

In [23]:
# 2. Which fruit costs more than 200?
print(prices[prices > 200])

Mango     250
Grapes    300
dtype: int64

In [24]:
# 3. Average price?
print(prices.mean())

200.0

In [25]:
# 4. Most expensive?
print(prices.max())

300

In [26]:

# 5. Get first 3?
print(prices[0:3])

Apple     100
Banana    200
Orange    150
dtype: int64

In [27]:
#dataframe - multiple series combined together 
#work on selection
import numpy as np 
import pandas as pd

In [ ]:
data = { 
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
pd.DataFrame(data)
#multiple series combined 
#df using dictionary

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
#create a dataframe using list
#cant provide keys
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
df2

#column names default

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [66]:
columns = ["Name","Age","City","Salary"]      #manually set columns
df2 = pd.DataFrame(data_list,columns =columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [30]:
#dict usage
student = {}  # Empty
student['name'] = 'Alice'
student['age'] = 25

print(student)
# {'name': 'Alice', 'age': 25}

{'name': 'Alice', 'age': 25}

In [31]:
student = {
    'name': 'Alice',
    'age': 25,
    'city': 'NYC'
}

In [32]:
# Access using key
student['name']      # 'Alice'
student['age']       # 25
student['city']      # 'NYC'

'NYC'

In [33]:
# Using .get() (safer - won't error if key missing)
student.get('name')  # 'Alice'
student.get('email')  # None (no error!)
student.get('email', 'Not found')  # 'Not found' (default value)

'Not found'

In [34]:
student = {'name': 'Alice', 'age': 25, 'city': 'NYC'}

# Get all keys
student.keys()       # dict_keys(['name', 'age', 'city'])
list(student.keys()) # ['name', 'age', 'city']

['name', 'age', 'city']

In [38]:
# Get all values
student.values()     # dict_values(['Alice', 25, 'NYC'])

dict_values(['Alice', 25, 'NYC'])

In [39]:
list(student.values()) # ['Alice', 25, 'NYC']

['Alice', 25, 'NYC']

In [40]:
# Get key-value pairs
student.items()      # dict_items([('name', 'Alice'), ('age', 25), ('city', 'NYC')])

dict_items([('name', 'Alice'), ('age', 25), ('city', 'NYC')])

In [41]:
list(student.items()) # [('name', 'Alice'), ('age', 25), ('city', 'NYC')]

[('name', 'Alice'), ('age', 25), ('city', 'NYC')]

In [45]:
#select and indexing of columns
df2[0]

KeyError: 0

In [ ]:
df2['Name']      #returns series

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [ ]:
df2.Name           #returns series

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: str

In [ ]:
df2[['Name', 'Age']]    #select columns

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [67]:
df2['Designation']=['manager','developer','developer','tester']

In [68]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000     manager
1   Anna   34     Paris   70000   developer
2  Peter   29    Berlin   62000   developer
3  Linda   42    London   85000      tester

In [ ]:
df2.drop('Designation',axis=1)    #by default axis=0, still in ram designation exists

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [70]:
df2

    Name  Age      City  Salary Designation
0   John   28  New York   65000     manager
1   Anna   34     Paris   70000   developer
2  Peter   29    Berlin   62000   developer
3  Linda   42    London   85000      tester

In [71]:
df2.drop('Designation',axis=1,inplace=True)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [72]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [73]:
df2.drop(["City","Salary"],axis=1)

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

In [74]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df2.drop(0,axis=0)          #inplace concept here also

    Name  Age    City  Salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [76]:
#how to access rows
df2[0]

KeyError: 0

In [77]:
df2.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [78]:
df2.loc[[0,1]]

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [79]:
df2.iloc[3]

Name       Linda
Age           42
City      London
Salary     85000
Name: 3, dtype: object

In [80]:
#subset of rows and columns
df2.loc[[0,1]][['City','Salary']]

       City  Salary
0  New York   65000
1     Paris   70000

In [81]:
df2.loc[[2,3]][['Name','Age']]

    Name  Age
2  Peter   29
3  Linda   42

In [82]:
#conditional selection
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [83]:
#see those ppl whose age is above 30
df2[df2['Age']>30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [85]:
#see those ppl whose age > 30 and their city must be paris
df2[df2['Age']>30 & df2['City']=='Paris']

TypeError: unsupported operand type(s) for &: 'int' and 'StringArray'

In [86]:
df2[df2['Age']>30 | df2['City']=='Paris']

TypeError: unsupported operand type(s) for |: 'int' and 'StringArray'

In [ ]:
df2[(df2['Age']>30) & (df2['City']=='Paris')]     #write in brackets ach condition

   Name  Age   City  Salary
1  Anna   34  Paris   70000

In [ ]:
df2[(df2['Age']>30) | (df2['City']=='Paris')]     #or operator

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [ ]:
#Missing data
#ml how to find and fill missing data

In [89]:
import numpy as np 
import pandas as pd

In [104]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [98]:
df

     A    B    C    D
0  1.0  NaN  1.0  1.0
1  2.0  2.0  2.0  NaN
2  NaN  3.0  3.0  NaN
3  4.0  4.0  NaN  NaN
4  5.0  5.0  NaN  5.0

Find missing data

In [99]:
df.isna()

       A      B      C      D
0  False   True  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [100]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [101]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [105]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [106]:
#remove missing data
#works on row basis
df.dropna()  #null values ki rows remove, sbme kuch na kuuch null values thi

     A  B    C    D
0  1.0  1  1.0  1.0

In [ ]:
df.dropna(thresh=3)   #atleast 3 non null values

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [108]:
df.dropna(thresh=5)

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [109]:
df.dropna(thresh=1)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [ ]:
#fulling nan, missing data

In [110]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [111]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [112]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

#inplace used to

In [113]:
values={'A':0,'B':100,'C':300,'D':400}
df.fillna(values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

#filling  fillna is vertical, dropping dropna is horizantal

In [ ]:
df.fillna(df.mean())      #pure df ka mean

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

In [ ]:
#dropna
#fillna
#isna

Merging, joining and concatenation

In [116]:
#merging two dataframes
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [117]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [118]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [120]:
pd.merge(employees,salaries,on='employee_id')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [ ]:
pd.merge(employees,salaries,on='employee_id',how='inner') #no null, only common, null are dander

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [123]:
pd.merge(employees,salaries,on='employee_id',how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [124]:
pd.merge(employees,salaries,on='employee_id',how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [125]:
pd.merge(employees,salaries,on='employee_id',how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

In [121]:
pd.merge(employees,salaries,on='name')

KeyError: 'name'

In [127]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [128]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [129]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [ ]:
pd.concat([df1,df2])  #pass a list

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [131]:
pd.concat(df1,df2)

TypeError: concat() takes 1 positional argument but 2 were given

In [ ]:
pd.concat([df2,df1])               #default axis=0, vertical.columns ke basis pe

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [135]:
pd.concat([df2,df1],axis=1)

    A   B   C   A   B   C
0  A3  B3  C3  A0  B0  C0
1  A4  B4  C4  A1  B1  C1
2  A5  B5  C5  A2  B2  C2

In [ ]:
#column, merge

In [ ]:
#joining two dfs

In [136]:
df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [137]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [138]:
df2

   score
2     85
3     90
4     75

In [ ]:
df1.join(df2)    #inner

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0

In [140]:
df1.join(df2,how='outer')    #inner

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [141]:
df2.join(df1)    #inner

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

In [142]:
#group by agregration
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [143]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [144]:
# Group by Category and calculate the sum of Sales

In [ ]:
df.groupby('Category')  #object created

In [ ]:
cat=df.groupby('Category')  #object created
cat
for i,v in cat:
    print(i)
    print(v)

A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07
B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [149]:
cat=df.groupby('Category')['Sales'].sum()  #object created
cat

Category
A    570
B    930
Name: Sales, dtype: int64

Yes, groupby() creates a GroupBy object, not a DataFrame. Let me explain how the loop works:
When you loop through a GroupBy object, it yields (group_name, group_data):
# Create GroupBy object
grouped = df.groupby('Category')

print("\nLoop through groups:")
for group_name, group_data in grouped:
    print(f"\n--- Group: {group_name} ---")
    print(group_data

df.groupby('Category')
        ↓
    GroupBy Object
        ↓
   For loop iterates
        ↓
  Yields (name, data) tuple
        ↓
  Unpack into i, v

In [193]:
cat=df.groupby('Store')['Sales'].sum()
cat

KeyError: 'Store'

In [ ]:
#qualitative - categorical data
#quantitative - numerical data- continuos
#group by qualitative , category store

In [ ]:
cat=df.groupby(['Category','Store'])['Sales'].sum()
cat
#group by multiple columns

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [ ]:
#Aggregation
#mean ,meadian mode std dev, variance
df['Sales'].mean() #mode, min max

np.float64(187.5)

In [ ]:
df['Sales'].median()

np.float64(190.0)

In [ ]:
df['Sales'].mode()

0    200
Name: Sales, dtype: int64

In [ ]:
df['Sales'].min()

np.int64(100)

In [ ]:
df['Sales'].max()

np.int64(300)

In [ ]:
df['Sales'].count()

np.int64(8)

In [ ]:
df['Sales'].agg(['mean','min','max'])

mean    187.5
min     100.0
max     300.0
Name: Sales, dtype: float64

Pivot tables, cross tabs

In [ ]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    156     88   John  January      Q1
1  2023-01-02       B   West    853     30   Mary  January      Q1
2  2023-01-03       C  North    277     40    Bob  January      Q1
3  2023-01-04       D  South    528     95  Alice  January      Q1
4  2023-01-05       A   East    530     68   John  January      Q1
5  2023-01-06       B   West    357     28   Mary  January      Q1
6  2023-01-07       C  North    606     81    Bob  January      Q1
7  2023-01-08       D  South    290     78  Alice  January      Q1
8  2023-01-09       A   East    504     90   John  January      Q1
9  2023-01-10       B   West    478     32   Mary  January      Q1
10 2023-01-11       C  North    245     97    Bob  January      Q1
11 2023-01-12       D  South    188     35  Alice  January      Q1
12 2023-01-13       A   East    946     42   John  January      Q1
13 2023-01-14       B   West    867     64   Mary  January      Q1
14 2023-01-15       C  North    533     84    Bob  January      Q1
15 2023-01-16       D  South    642     38  Alice  January      Q1
16 2023-01-17       A   East    365     95   John  January      Q1
17 2023-01-18       B   West    116     47   Mary  January      Q1
18 2023-01-19       C  North    614     59    Bob  January      Q1
19 2023-01-20       D  South    542     92  Alice  January      Q1

In [ ]:
#sep on basis of region region 
pd.pivot_table(df,values='Sales',index='Region', columns='Product')
#its a pivot table
#500.25 is mean of sales

Product      A      B      C      D
Region
East     500.2    NaN    NaN    NaN
North      NaN    NaN  455.0    NaN
South      NaN    NaN    NaN  438.0
West       NaN  534.2    NaN    NaN

In [ ]:
#mean, median mode 
pd.pivot_table(df,values='Sales',index='Region', columns='Product',aggfunc='median')

Product      A      B      C      D
Region
East     504.0    NaN    NaN    NaN
North      NaN    NaN  533.0    NaN
South      NaN    NaN    NaN  528.0
West       NaN  478.0    NaN    NaN

In [ ]:
#poivot table khud se bana skata hai
#use case heatmap clustere, seaborn matplotlib
pivot2=pd.pivot_table(df,values=['Sales','Units'],index='Region', columns='Product',aggfunc='median')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     504.0    NaN    NaN    NaN  88.0   NaN   NaN   NaN
North      NaN    NaN  533.0    NaN   NaN   NaN  81.0   NaN
South      NaN    NaN    NaN  528.0   NaN   NaN   NaN  78.0
West       NaN  478.0    NaN    NaN   NaN  32.0   NaN   NaN

In [ ]:
pivot2=pd.pivot_table(df,values=['Quarter','Units'],index='Region', columns='Product',aggfunc='median')
#dtype 'str' does not support operation 'median'
pivot2

TypeError: dtype 'str' does not support operation 'median'

In [ ]:
#crosstab.
#use count 
pd.crosstab(df['Region'],df['Product'])   #counting same as before just count

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

**Operations**

In [ ]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})

In [ ]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
#data preprocessing for training ml algo

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
#operation 1 
#shape attrib
df.shape

(20, 8)

In [ ]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [ ]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [ ]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [ ]:
df1['A']+10 #broadcasting

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [ ]:
#when new data comes, we do all above steps

In [ ]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
#do squre root of all values in B
#create function
def square(x):
    return x**2
#apply function on any one column of df
df1['B'].apply(square)

0     100
1     400
2     900
3    1600
4    2500
Name: B, dtype: int64

In [ ]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [ ]:
df1['B']=df1['B'].apply(square)
df1

   A        B    C
0  1    10000  100
1  2   160000  200
2  3   810000  300
3  4  2560000  400
4  5  6250000  500

In [ ]:
df1['D']=df1['B'].apply(square)
df1

   A        B    C               D
0  1    10000  100       100000000
1  2   160000  200     25600000000
2  3   810000  300    656100000000
3  4  2560000  400   6553600000000
4  5  6250000  500  39062500000000

In [ ]:
#lamda
df1['A']=df1['B'].apply(lambda x: x**2)
df1

                A        B    C               D
0       100000000    10000  100       100000000
1     25600000000   160000  200     25600000000
2    656100000000   810000  300    656100000000
3   6553600000000  2560000  400   6553600000000
4  39062500000000  6250000  500  39062500000000

#Feature extraction on real dataa , here apply function used

In [195]:
#datasource not from pndas or numpy
#but csv and excel- rows and columns
#pandas support a lot of formats
df=pd.read_csv(r'anime.csv')
#raw string
#read excel

In [ ]:
df.head() #top 5 rows

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [197]:
#make a new column for episode count
#make a new column for time stamp
#which anime has the highest score
#give me top 5 highest scoring anime
#which anime has the highest episode count
#animes with top 5 episode count
#which is the longest running anime

In [200]:
#make a new column for episode count
#feature extraction
df.loc[1]
#everytitle has sep ep count

Rank                                                     2
Title    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
Score                                                 9.07
Name: 1, dtype: object

In [201]:
df.loc[1]['Title']

'Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members'

In [202]:
df.loc[1]['Title']

'Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members'

In [207]:
def extract_episode_count(text):
    #send all titles to this function
    check=False
    data=""
    for i in text:
        if i==')':
            break
        if i=='(':
            check=True
            continue
        if check==True:
            data+=i
    return data

In [ ]:
#apply on title each title
df['Title'].apply(extract_episode_count) 
#dont change title but new columns

0      64 eps
1      24 eps
2      13 eps
3      51 eps
4      10 eps
5      51 eps
6       1 eps
7     148 eps
8      13 eps
9      13 eps
10      2 eps
11    110 eps
12     13 eps
13     13 eps
14     12 eps
15    201 eps
16      1 eps
17     22 eps
18     24 eps
19     25 eps
20      1 eps
21      1 eps
22      7 eps
23     14 eps
24     74 eps
25      1 eps
26      1 eps
27     12 eps
28      1 eps
29     24 eps
30     23 eps
31     12 eps
32     26 eps
33     13 eps
34     16 eps
35     11 eps
36      1 eps
37     11 eps
38     10 eps
39      1 eps
40     26 eps
41     12 eps
42     75 eps
43     26 eps
44     26 eps
45     24 eps
46     10 eps
47     12 eps
48     12 eps
49      4 eps
Name: Title, dtype: str

In [209]:
df['episode_count']=df['Title'].apply(extract_episode_count)

In [ ]:
df #remove space eps

,Rank,Title,Score,episode_count
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64 eps
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24 eps
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13 eps
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51 eps
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10 eps
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51 eps
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1 eps
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148 eps
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13 eps
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13 eps
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2 eps
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110 eps
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13 eps
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13 eps
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12 eps
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201 eps
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1 eps
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22 eps
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24 eps
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25 eps
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1 eps
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1 eps
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7 eps
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14 eps
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74 eps
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1 eps
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1 eps
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12 eps
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1 eps
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24 eps
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23 eps
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12 eps
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26 eps
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13 eps
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16 eps
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11 eps
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1 eps
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11 eps
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10 eps
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1 eps
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26 eps
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12 eps
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75 eps
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26 eps
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26 eps
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24 eps
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10 eps
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12 eps
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12 eps
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4 eps

In [211]:
df['episode_count']=df['episode_count'].str.replace(' eps','')

In [212]:
df

,Rank,Title,Score,episode_count
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4

In [213]:
df.iloc[0]['episode_count']

'64'

In [214]:
type(df.iloc[0]['episode_count'])

str

In [215]:
df['episode_count']=df['episode_count'].astype(int)

In [216]:
df

,Rank,Title,Score,episode_count
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4

In [ ]:
#first feature extraction
#by applying a function on title

In [217]:
#feature extraction on timestamp
df.loc[0]['Title']
#make a new column for time stamp

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [218]:
df.loc[1]['Title']

'Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members'

BRACKET CLOSE THEN TIME STAMP STARTS, OR there is a dash in between the strings before that and after that can be used. 18 letters

In [233]:
def extract_timestamp(text):
    check=False
    data=""
    for i in range(len(text)):
        if text[i]==')':
            for j in range(i+1,i+20):
                data+=text[j]
            break
    return data

In [234]:
df['Title'].apply(extract_timestamp)

0     Apr 2009 - Jul 2010
1     Apr 2011 - Sep 2011
2     Oct 2022 - Dec 2022
3     Apr 2015 - Mar 2016
4     Apr 2019 - Jul 2019
5     Apr 2011 - Mar 2012
6     Jan 2021 - Jan 2021
7     Oct 2011 - Sep 2014
8     Apr 2022 - Jun 2022
9     Oct 2012 - Mar 2013
10    Mar 2023 - May 2023
11    Jan 1988 - Mar 1997
12    Jul 2023 - Aug 2023
13    Apr 2021 - Jun 2021
14    Jan 2017 - Mar 2017
15    Apr 2006 - Mar 2010
16    Sep 2016 - Sep 2016
17    Oct 2017 - Mar 2018
18    Oct 2008 - Mar 2009
19    Apr 2008 - Sep 2008
20    Jul 2013 - Jul 2013
21    Sep 2020 - Sep 2020
22    Aug 2017 - Aug 2017
23    Jul 2018 - Oct 2018
24    Apr 2004 - Sep 2005
25    Aug 2016 - Aug 2016
26    Dec 2022 - Dec 2022
27    Oct 2022 - Dec 2022
28    Dec 2022 - Dec 2022
29    Jan 2023 - Jun 2023
30    Jul 2023 - Aug 2023
31    Jan 2018 - Mar 2018
32    Apr 2020 - Oct 2021
33    Jan 2019 - Apr 2019
34    Dec 2020 - Mar 2021
35    Dec 2021 - Feb 2022
36    Jan 2017 - Jan 2017
37    Apr 2023 - Jun 2023
38    Oct 2016 - Dec 2016
39    Jul 2001 - Jul 2001
40    Jul 2013 - Dec 2013
41    Jan 2022 - Apr 2022
42    Oct 2000 - Mar 2002
43    Apr 1998 - Apr 1999
44    Apr 2022 - Oct 2022
45    Jul 2019 - Dec 2019
46    Oct 2014 - Dec 2014
47    Jan 2017 - Mar 2017
48    Oct 2022 - Dec 2022
49    Feb 1999 - Sep 1999
Name: Title, dtype: str

In [ ]:
df['timestamp']=df['Title'].apply(extract_timestamp)
df


#months extract to do
#python less fucntions
#total time se months extract

,Rank,Title,Score,episode_count,timestamp
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51,Apr 2011 - Mar 2012
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1,Jan 2021 - Jan 2021
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13,Apr 2022 - Jun 2022
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13,Oct 2012 - Mar 2013
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,Mar 2023 - May 2023
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13,Jul 2023 - Aug 2023
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13,Apr 2021 - Jun 2021
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12,Jan 2017 - Mar 2017
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1,Sep 2016 - Sep 2016
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22,Oct 2017 - Mar 2018
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24,Oct 2008 - Mar 2009
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25,Apr 2008 - Sep 2008
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1,Jul 2013 - Jul 2013
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1,Sep 2020 - Sep 2020
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7,Aug 2017 - Aug 2017
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14,Jul 2018 - Oct 2018
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1,Aug 2016 - Aug 2016
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1,Dec 2022 - Dec 2022
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12,Oct 2022 - Dec 2022
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1,Dec 2022 - Dec 2022
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24,Jan 2023 - Jun 2023
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23,Jul 2023 - Aug 2023
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12,Jan 2018 - Mar 2018
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,Apr 2020 - Oct 2021
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13,Jan 2019 - Apr 2019
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16,Dec 2020 - Mar 2021
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11,Dec 2021 - Feb 2022
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1,Jan 2017 - Jan 2017
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11,Apr 2023 - Jun 2023
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10,Oct 2016 - Dec 2016
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1,Jul 2001 - Jul 2001
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26,Jul 2013 - Dec 2013
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12,Jan 2022 - Apr 2022
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26,Apr 1998 - Apr 1999
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26,Apr 2022 - Oct 2022
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24,Jul 2019 - Dec 2019
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10,Oct 2014 - Dec 2014
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12,Jan 2017 - Mar 2017
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12,Oct 2022 - Dec 2022
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4,Feb 1999 - Sep 1999

In [238]:
from datetime import datetime

def extract_total_months(date_range):
    # Example: "Apr 2009 - Jul 2010"
    if ' - ' not in date_range:
        return 0
    
    try:
        # Split by ' - '
        start_str, end_str = date_range.split(' - ')
        
        # Parse dates
        start_date = datetime.strptime(start_str.strip(), '%b %Y')
        end_date = datetime.strptime(end_str.strip(), '%b %Y')
        
        # Calculate months
        months = (end_date.year - start_date.year) * 12 + \
                 (end_date.month - start_date.month)
        
        return months
    except:
        return 0

# Test
print(extract_total_months("Apr 2009 - Jul 2010"))  # 15

# Use with Pandas
df['Total_Months'] = df['timestamp'].apply(extract_total_months)

15

In [239]:
df

,Rank,Title,Score,episode_count,timestamp,Total_Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,15
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,5
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,2
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,11
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,3
5,6,"Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...",9.04,51,Apr 2011 - Mar 2012,11
6,7,Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...,9.04,1,Jan 2021 - Jan 2021,0
7,8,Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...,9.04,148,Oct 2011 - Sep 2014,35
8,9,Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...,9.04,13,Apr 2022 - Jun 2022,2
9,10,Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...,9.03,13,Oct 2012 - Mar 2013,5
10,11,Shingeki no Kyojin: The Final Season - Kankets...,9.03,2,Mar 2023 - May 2023,2
11,12,Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...,9.02,110,Jan 1988 - Mar 1997,110
12,13,Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...,8.99,13,Jul 2023 - Aug 2023,1
13,14,Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...,8.99,13,Apr 2021 - Jun 2021,2
14,15,"Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...",8.98,12,Jan 2017 - Mar 2017,2
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,47
16,17,Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...,8.94,1,Sep 2016 - Sep 2016,0
17,18,3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...,8.93,22,Oct 2017 - Mar 2018,5
18,19,Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...,8.93,24,Oct 2008 - Mar 2009,5
19,20,Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...,8.91,25,Apr 2008 - Sep 2008,5
20,21,Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...,8.91,1,Jul 2013 - Jul 2013,0
21,22,Violet Evergarden MovieMovie (1 eps)Sep 2020 -...,8.89,1,Sep 2020 - Sep 2020,0
22,23,Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...,8.88,7,Aug 2017 - Aug 2017,0
23,24,Gintama.: Shirogane no Tamashii-hen - Kouhan-s...,8.88,14,Jul 2018 - Oct 2018,3
24,25,"MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...",8.87,74,Apr 2004 - Sep 2005,17
25,26,Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...,8.84,1,Aug 2016 - Aug 2016,0
26,27,Kaguya-sama wa Kokurasetai: First Kiss wa Owar...,8.84,1,Dec 2022 - Dec 2022,0
27,28,Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...,8.83,12,Oct 2022 - Dec 2022,2
28,29,The First Slam DunkMovie (1 eps)Dec 2022 - Dec...,8.83,1,Dec 2022 - Dec 2022,0
29,30,Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...,8.82,24,Jan 2023 - Jun 2023,5
30,31,Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...,8.82,23,Jul 2023 - Aug 2023,1
31,32,Gintama.: Shirogane no Tamashii-henTV (12 eps)...,8.81,12,Jan 2018 - Mar 2018,2
32,33,Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...,8.81,26,Apr 2020 - Oct 2021,18
33,34,Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...,8.80,13,Jan 2019 - Apr 2019,3
34,35,Shingeki no Kyojin: The Final SeasonTV (16 eps...,8.80,16,Dec 2020 - Mar 2021,3
35,36,Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...,8.79,11,Dec 2021 - Feb 2022,2
36,37,Kizumonogatari III: Reiketsu-henMovie (1 eps)J...,8.79,1,Jan 2017 - Jan 2017,0
37,38,"""Oshi no Ko""TV (11 eps)Apr 2023 - Jun 2023645,...",8.79,11,Apr 2023 - Jun 2023,2
38,39,Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...,8.78,10,Oct 2016 - Dec 2016,2
39,40,Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...,8.78,1,Jul 2001 - Jul 2001,0
40,41,Monogatari Series: Second SeasonTV (26 eps)Jul...,8.77,26,Jul 2013 - Dec 2013,5
41,42,Shingeki no Kyojin: The Final Season Part 2TV ...,8.77,12,Jan 2022 - Apr 2022,3
42,43,Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...,8.76,75,Oct 2000 - Mar 2002,17
43,44,"Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...",8.75,26,Apr 1998 - Apr 1999,12
44,45,Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...,8.75,26,Apr 2022 - Oct 2022,6
45,46,"Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...",8.74,24,Jul 2019 - Dec 2019,5
46,47,Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...,8.73,10,Oct 2014 - Dec 2014,2
47,48,Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...,8.72,12,Jan 2017 - Mar 2017,2
48,49,Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...,8.71,12,Oct 2022 - Dec 2022,2
49,50,Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...,8.71,4,Feb 1999 - Sep 1999,7

In [ ]:
#base case scenario of feature extraction
#we need these features to improve accuracy of ml model

#which anime has highest score

In [240]:
df[df['Score']==df['Score'].max()]

,Rank,Title,Score,episode_count,timestamp,Total_Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 2010,15

In [243]:
df[df['Score']==df['Score'].max()]['Title']

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
Name: Title, dtype: str

In [244]:
df['Score'].value_counts()

Score
9.04    4
8.79    3
9.06    2
9.03    2
8.99    2
8.94    2
8.93    2
8.91    2
8.88    2
8.84    2
8.83    2
8.82    2
8.81    2
8.80    2
8.78    2
8.77    2
8.75    2
8.71    2
9.10    1
9.07    1
9.05    1
9.02    1
8.98    1
8.89    1
8.87    1
8.76    1
8.74    1
8.73    1
8.72    1
Name: count, dtype: int64

In [245]:
df['Score'].unique()

array([9.1 , 9.07, 9.06, 9.05, 9.04, 9.03, 9.02, 8.99, 8.98, 8.94, 8.93,
       8.91, 8.89, 8.88, 8.87, 8.84, 8.83, 8.82, 8.81, 8.8 , 8.79, 8.78,
       8.77, 8.76, 8.75, 8.74, 8.73, 8.72, 8.71])

In [248]:

#give me top 5 highest scoring anime
df['Title'].head()

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: str

In [247]:
#make a new column for episode count
#make a new column for time stamp
#which anime has the highest score
#give me top 5 highest scoring anime
#which anime has the highest episode count
#animes with top 5 episode count
#which is the longest running anime

In [249]:
#which anime has the highest episode count
df[df['episode_count']==df['episode_count'].max()]

,Rank,Title,Score,episode_count,timestamp,Total_Months
15,16,"GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...",8.94,201,Apr 2006 - Mar 2010,47